### ISSUE TITLE
Try to verify and contract and having the following error.

### ISSUE THREAD

**Issue by cryptoseabook** [PatrickAlphaC/dungeons-and-dragons-nft#5]
Installed the truffle-verify-plugin
and run command ```truffle run verify DungeonsAndDragonsCharacter --network rinkeby --license MIT```

Giving following error:
Verifying DungeonsAndDragonsCharacter
Cannot find module '@chainlink/contracts/src/v0.6/VRFConsumerBase.sol'

**Comment by PatrickAlphaC** [comment]
I made a few changes. Could you repull then run `yarn`?

**Comment by PatrickAlphaC** [comment]
Closing for now
