### ISSUE TITLE
Dynamic variable experience

### ISSUE THREAD

**Issue by oriolorra** [PatrickAlphaC/dungeons-and-dragons-nft#6]
Hi Patrick,

I am new into this world, and this could be a trivial question. But, I do not see how is **experience** parameter/variable of the NFT changed. How? Where? 

Sorry, but you can explain a little this?

Thanks in advance,

**Comment by PatrickAlphaC** [comment]
Sorry, didn't see this till now! And great question, right now, experience doesn't have any use. It can be ignored.
