### ISSUE TITLE
d&d not deploying to network 

### ISSUE THREAD

**Issue by chahakshah111** [PatrickAlphaC/dungeons-and-dragons-nft#7]
when i run truffle migrate --reset --network rinkeby its not stopping and after completing 50 blocks i got timeout Error.

i tried configuring provider object like this: 
    rinkeby: {
      provider: () => {
        return new HDWalletProvider(MNEMONIC, rinkebyNodeUrl);
      },
      network_id: "4",
      gas: 5000000,
      networkCheckTimeout: 1000000,
      timeoutBlocks: 200,
    },

but its still not working, how can i solve this issue?
![Screenshot (15)](https://user-images.githubusercontent.com/81607081/123420376-1f056980-d5d9-11eb-8096-2a20a44bb16b.png)

**Comment by PatrickAlphaC** [comment]
Thanks for this. 
 
Could you reclone and try now? I just updated the project.
